/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fifo;

import java.awt.List;
import java.util.ArrayList;

/**
 *
 * @author H P
 */
public class initial_window extends javax.swing.JFrame {

    static int llegada = 0;
    static int esperaTodos = 0;
    static int retornoTodos = 0;
    
    static ArrayList<Proc> procesos = new ArrayList<Proc>();
    
   
    
    
    /**
     * Creates new form initial_window
     */
    public initial_window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ejec_proc2 = new javax.swing.JToggleButton();
        ejec_proc3 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        terminar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        ejec_proc2.setText("programa2");
        ejec_proc2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ejec_proc2MouseClicked(evt);
            }
        });

        ejec_proc3.setText("programa3");
        ejec_proc3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ejec_proc3MouseClicked(evt);
            }
        });
        ejec_proc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejec_proc3ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(242, 2, 24));

        terminar.setForeground(new java.awt.Color(255, 255, 255));
        terminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        terminar.setText("Terminar Simulación");
        terminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                terminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(terminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(terminar, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fifo/static/icons8-basketball-48.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(497, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(ejec_proc2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(84, 84, 84)
                    .addComponent(ejec_proc3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(693, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(ejec_proc2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(ejec_proc3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(401, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    class Proc{
        String name;
        int tiempoLlegada;
        int tiempoEjecucuion;
        int tiempoEspera;
        int tiempoRetorno;
        
        
        public Proc(String name, int tiempoLlegada, int tiempoEjecucion){
            this.name = name;
            this.tiempoEjecucuion = tiempoEjecucion;
            this.tiempoLlegada = tiempoLlegada;
            
        }
    }
    private void ejec_proc2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ejec_proc2MouseClicked
        var e = new Proc("proc1", llegada, 5);        
        e.tiempoEspera = esperaTodos - e.tiempoLlegada;
        llegada++;
        
         secundary_window ven = new secundary_window(e.name);
        ven.setVisible(true);
        
        retornoTodos += e.tiempoEjecucuion;
        e.tiempoRetorno = retornoTodos;
        
        procesos.add(e);
        
        for (Proc proceso : procesos) {
            System.out.print(proceso.name + " ");
        }
        System.out.println("");
        
        
    }//GEN-LAST:event_ejec_proc2MouseClicked

    private void ejec_proc3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ejec_proc3MouseClicked
        // TODO add your handling code here:                 
        
        var e = new Proc("proc3", llegada, 5);        
        e.tiempoEspera = esperaTodos - e.tiempoLlegada;
        llegada++;
        
        secundary_window ven = new secundary_window(e.name);
        ven.setVisible(true);
        
        retornoTodos += e.tiempoEjecucuion;
        e.tiempoRetorno = retornoTodos;
        
        procesos.add(e);
        
        for (Proc proceso : procesos) {
            System.out.print(proceso.name + " ");
        }
        System.out.println("");
    }//GEN-LAST:event_ejec_proc3MouseClicked

    private void ejec_proc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejec_proc3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ejec_proc3ActionPerformed

    private void terminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_terminarMouseClicked
        Results newWindow = new Results(procesos);
        newWindow.setVisible(true);
    }//GEN-LAST:event_terminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(initial_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(initial_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(initial_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(initial_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new initial_window().setVisible(true);
                
            }
        });
        
        for (Proc proceso : procesos) {
            System.out.print(proceso.name + " ");
        }
        System.out.println("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ejec_proc2;
    private javax.swing.JToggleButton ejec_proc3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel terminar;
    // End of variables declaration//GEN-END:variables
}
